name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/starthub-ai:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/starthub-ai:latest
            docker stop starthub-container && docker rm starthub-container || true
            docker run -d -p 8000:8000 --env-file .env --name starthub-container --restart unless-stopped ${{ secrets.DOCKERHUB_USERNAME }}/starthub-ai:latest
